package com.ab.models;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Student {
	
	@Id
	private int id;
	
	private String name;
	
	private String email;
	
	public Student() { // this was required in the findAll() function, automatically generated by the compiler if no constructors have been defined for the class
		super();
	}

	public Student(int id, String name, String email) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public String getEmail() {
		return email;
	}

//	@Override
//	public String toString() {
//		return "Student [id=" + id + ", name=" + name + ", email=" + email + "]";
//	}
//	
	
	

}
